apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xxl-job
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10Gi