apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gp-service
  name: gp-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gp-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gp-service
    spec:
      containers:
      - image: 10.101.2.123/library/gp-service:20230718180116
        imagePullPolicy: Always
        name: gp-service
        ports:
        - containerPort: 5000
        resources: {}
status: {}
