apiVersion: v1
kind: Service
metadata:
  name: gp-service
  namespace: dev
  labels:
    app: gp-service
spec:
  type: ClusterIP
  selector:
    app: gp-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000