apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-center-service
  name: user-center-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-center-service
  template:
    metadata:
      labels:
        app: user-center-service
    spec:
      containers:
      - image: 10.101.2.123/library/user-center-service:{{ .tag }}
        imagePullPolicy: IfNotPresent
        name: user-center-service
        ports:
        - containerPort: 9497