apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ci-workflows
  resources:
    requests:
      storage: 10Gi