apiVersion: v1
kind: PersistentVolume
metadata:
  name: ci-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ci
  hostPath:
    path: /data/share/ci