apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi