apiVersion: v1
kind: PersistentVolume
metadata:
  name: ci
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ci-workflows
  hostPath:
    path: /data/front