apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: argo
  name: frontend-ci-template
spec:
  ttlstrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowCompletion
  arguments:
    parameters:
      - name: branch
        value: main
      - name: artifactBuildArgs
        value: ""
      - name: appPath
        value: ""
      - name: appName
        value: ""
      - name: shellBeforeBuild
        value: ""
      - name: shellAfterBuild
        value: ""
      - name: tag
        value: ""
      - name: builderName
        value: 10.101.2.123/cache/pnpm-base:v1.0
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: ci-artifact
        namespace: argo
      spec:
        accessModes: [ ReadWriteMany ]
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
          - name: artifact-build
            template: artifact-build
            dependencies:
              - clone
    - name: clone
      container:
        env:
          - name: GITLAB_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitlab-access-token
                key: token
        volumeMounts:
          - mountPath: /ci/code
            name: ci-artifact
            subPath: code
        image: 10.101.2.123/library/git:2.41.0
        workingDir: /ci
        command: [ sh, -euc ]
        args:
          - |
            cd code
            echo "git clone -v -b {{workflow.parameters.branch}} --single-branch --depth 1"
            git clone -v -b "{{workflow.parameters.branch}}" --single-branch --depth 1 http://wansheng:$GITLAB_ACCESS_TOKEN@10.101.1.50/{{workflow.parameters.appPath}}.git .
    - name: artifact-build
      nodeSelector:
        brand.io/arch: frontend
      container:
        volumeMounts:
          - mountPath: /ci
            name: ci-artifact
            subPath: code
          - mountPath: /data
            name: ci
        image: "{{workflow.parameters.builderName}}"
        workingDir: /ci
        command: [ sh, -c ]
        env:
          - name: TZ
            value: Asia/Shanghai
        args:
          - |
            [ -n "{{workflow.parameters.shellBeforeBuild}}" ] && {{workflow.parameters.shellBeforeBuild}}
            {{workflow.parameters.artifactBuildArgs}}
            [ -n "{{workflow.parameters.shellAfterBuild}}" ] && {{workflow.parameters.shellAfterBuild}}
            if [ -d /data/dev/{{workflow.parameters.appName}} ]; then
              rm -rf /data/dev/{{workflow.parameters.appName}}
            fi
            mkdir -p /data/dev/{{workflow.parameters.appName}}
            cp -r dist/* /data/dev/{{workflow.parameters.appName}}
  volumes:
    - name: harbor-secret
      secret:
        secretName: harbor-secret
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: ci
      persistentVolumeClaim:
        claimName: ci