apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: dev
  labels:
    app: monitor
spec:
  type: ClusterIP
  selector:
    app: monitor
  ports:
    - name: http
      port: 8091
      targetPort: 8091
