apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/kaniko/maven-logs