apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: load-dockerfile-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: load-dockerfile
  resources:
    requests:
      storage: 1Gi