apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: mysql
  labels:
    org: brand
    env: dev
spec:
  type: NodePort
  selector:
    app: demo
    env: dev
  ports:
    - name: http
      port: 9060
      targetPort: 9060
      nodePort: 31065