apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - image: 10.101.2.123/library/keycloak-21.1.2:20230714144351
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080